<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Teacher;
use Illuminate\Support\Facades\Hash;

class TeacherSeeder extends Seeder
{
    public function run(): void
    {
        $users = [
            [
                'username' => '3603141004660008',
                'name' => 'H. Jayadi ,S.Pd',
                'email' => '-jayadi-@gentasyahputra.sch.id',
                'password' => Hash::make('3603141004660008'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603141102960006',
                'name' => 'Fira Ferista ,S.Pd',
                'email' => 'fira-ferista-@gentasyahputra.sch.id',
                'password' => Hash::make('3603141102960006'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603141112510004',
                'name' => 'Yudho Putranto, S,Pd',
                'email' => 'yudho-putranto@gentasyahputra.sch.id',
                'password' => Hash::make('3603141112510004'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603130405520001',
                'name' => 'Basri Lastiawan, S,Pd',
                'email' => 'basri-lastiawan@gentasyahputra.sch.id',
                'password' => Hash::make('3603130405520001'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603132209690002',
                'name' => 'Warsa Sutrisna, S.H',
                'email' => 'warsa-sutrisna@gentasyahputra.sch.id',
                'password' => Hash::make('3603132209690002'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603140706610001',
                'name' => 'Abdul Mukti, S,Pd',
                'email' => 'abdul-mukti@gentasyahputra.sch.id',
                'password' => Hash::make('3603140706610001'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603132608900004',
                'name' => 'Andri Darmawan, S.Pd',
                'email' => 'andri-darmawan@gentasyahputra.sch.id',
                'password' => Hash::make('3603132608900004'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3671070505770008',
                'name' => 'A.Muhaimin, S.Pd.I',
                'email' => 'amuhaimin@gentasyahputra.sch.id',
                'password' => Hash::make('3671070505770008'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3671104309030002',
                'name' => 'Diana Lulu K, S.Psi',
                'email' => 'diana-lulu-k@gentasyahputra.sch.id',
                'password' => Hash::make('3671104309030002'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603144103870011',
                'name' => 'Dini Nuraini, S.Pd',
                'email' => 'dini-nuraini@gentasyahputra.sch.id',
                'password' => Hash::make('3603144103870011'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603146405010004',
                'name' => 'Ditha Puteri T M , S.Pd',
                'email' => 'ditha-puteri-t-m-@gentasyahputra.sch.id',
                'password' => Hash::make('3603146405010004'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603137005000001',
                'name' => 'Fairuz Shofa Kamila S.Pd',
                'email' => 'fairuz-shofa-kamila-spd@gentasyahputra.sch.id',
                'password' => Hash::make('3603137005000001'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603140202920007',
                'name' => 'Ferry Diansah',
                'email' => 'ferry-diansah@gentasyahputra.sch.id',
                'password' => Hash::make('3603140202920007'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603134307940001',
                'name' => 'Hamlahu Fikah, S.Pd',
                'email' => 'hamlahu-fikah@gentasyahputra.sch.id',
                'password' => Hash::make('3603134307940001'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603134801000001',
                'name' => 'Inez Afifah Nurfitriani, S.Pd.',
                'email' => 'inez-afifah-nurfitriani@gentasyahputra.sch.id',
                'password' => Hash::make('3603134801000001'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603130410920001',
                'name' => 'M. Ishadi Khamarullah, S.Pd',
                'email' => 'm-ishadi-khamarullah@gentasyahputra.sch.id',
                'password' => Hash::make('3603130410920001'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603130303870016',
                'name' => 'Marwan Setiawan, S.Pd',
                'email' => 'marwan-setiawan@gentasyahputra.sch.id',
                'password' => Hash::make('3603130303870016'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603136709870003',
                'name' => 'Maryanih, S.Pd',
                'email' => 'maryanih@gentasyahputra.sch.id',
                'password' => Hash::make('3603136709870003'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603130712930004',
                'name' => 'Miftahudin, S.Pd.I',
                'email' => 'miftahudin@gentasyahputra.sch.id',
                'password' => Hash::make('3603130712930004'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603141012890005',
                'name' => 'Nanang husen',
                'email' => 'nanang-husen@gentasyahputra.sch.id',
                'password' => Hash::make('3603141012890005'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603135207900007',
                'name' => 'Ninis Khairunnisa, S.Pd',
                'email' => 'ninis-khairunnisa@gentasyahputra.sch.id',
                'password' => Hash::make('3603135207900007'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '23',
                'name' => 'Patmawati, S.Pd',
                'email' => 'patmawati@gentasyahputra.sch.id',
                'password' => Hash::make('23'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603132203910001',
                'name' => 'Rama Rabianto, S.Pd',
                'email' => 'rama-rabianto@gentasyahputra.sch.id',
                'password' => Hash::make('3603132203910001'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603131404910006',
                'name' => 'Rudi, S.Pd',
                'email' => 'rudi@gentasyahputra.sch.id',
                'password' => Hash::make('3603131404910006'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603146208960001',
                'name' => 'Siti Chandra Wulan, S.Pd',
                'email' => 'siti-chandra-wulan@gentasyahputra.sch.id',
                'password' => Hash::make('3603146208960001'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603135003960009',
                'name' => 'Siti Hopipah, S.Pd',
                'email' => 'siti-hopipah@gentasyahputra.sch.id',
                'password' => Hash::make('3603135003960009'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603131508840006',
                'name' => 'Susanto, S.Pd',
                'email' => 'susanto@gentasyahputra.sch.id',
                'password' => Hash::make('3603131508840006'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603155007000002',
                'name' => 'Tamara Tri Utami, S.Si',
                'email' => 'tamara-tri-utami@gentasyahputra.sch.id',
                'password' => Hash::make('3603155007000002'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603142303970005',
                'name' => 'Yudi Ahmad Rizaldi, S.Pd',
                'email' => 'yudi-ahmad-rizaldi@gentasyahputra.sch.id',
                'password' => Hash::make('3603142303970005'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603132410940001',
                'name' => 'Irwan Supriawan Syah,S.Pd',
                'email' => 'irwan-supriawan-syah@gentasyahputra.sch.id',
                'password' => Hash::make('3603132410940001'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603144506740004',
                'name' => 'Herawati ,S.Pd',
                'email' => 'herawati-@gentasyahputra.sch.id',
                'password' => Hash::make('3603144506740004'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603132011930004',
                'name' => 'Ahmat Supriyadi,S.Kom',
                'email' => 'ahmat-supriyadi@gentasyahputra.sch.id',
                'password' => Hash::make('3603132011930004'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603140212650005',
                'name' => 'Jamid Bin Pulung',
                'email' => 'jamid-bin-pulung@gentasyahputra.sch.id',
                'password' => Hash::make('3603140212650005'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603135712880002',
                'name' => 'Murni',
                'email' => 'murni@gentasyahputra.sch.id',
                'password' => Hash::make('3603135712880002'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603130906860002',
                'name' => 'Usuf',
                'email' => 'usuf@gentasyahputra.sch.id',
                'password' => Hash::make('3603130906860002'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3604141301020002',
                'name' => 'Genta Syadilla Putra, S.Pd',
                'email' => 'genta-syadilla-putra@gentasyahputra.sch.id',
                'password' => Hash::make('3604141301020002'),
                'role' => 'guru',
                'gender' => 'man',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'username' => '3603134311850003',
                'name' => 'Novi Jayanti',
                'email' => 'novi-jayanti@gentasyahputra.sch.id',
                'password' => Hash::make('3603134311850003'),
                'role' => 'guru',
                'gender' => 'woman',
                'email_verified_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        User::insert($users);

        $userIds = User::where('role', 'guru')->pluck('id', 'username');
        $teachers = [
            [
                'user_id' => $userIds['3603141004660008'] ?? null,
                'nip' => '3603141004660008',
                'assigned_class' => 'XI B 1',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603141102960006'] ?? null,
                'nip' => '3603141102960006',
                'assigned_class' => 'XI B 2',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603141112510004'] ?? null,
                'nip' => '3603141112510004',
                'assigned_class' => 'XI A 1',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603130405520001'] ?? null,
                'nip' => '3603130405520001',
                'assigned_class' => 'X1 A 2',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603132209690002'] ?? null,
                'nip' => '3603132209690002',
                'assigned_class' => 'XI B 3',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603140706610001'] ?? null,
                'nip' => '3603140706610001',
                'assigned_class' => 'XII MIPA 1',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603132608900004'] ?? null,
                'nip' => '3603132608900004',
                'assigned_class' => 'XII MIPA 2',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3671070505770008'] ?? null,
                'nip' => '3671070505770008',
                'assigned_class' => 'XII IPS 1',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3671104309030002'] ?? null,
                'nip' => '3671104309030002',
                'assigned_class' => 'XII IPS 2',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603144103870011'] ?? null,
                'nip' => '3603144103870011',
                'assigned_class' => 'XII IPS 3',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603146405010004'] ?? null,
                'nip' => '3603146405010004',
                'assigned_class' => 'X.1',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603137005000001'] ?? null,
                'nip' => '3603137005000001',
                'assigned_class' => 'X.2',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603140202920007'] ?? null,
                'nip' => '3603140202920007',
                'assigned_class' => 'X.3',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603134307940001'] ?? null,
                'nip' => '3603134307940001',
                'assigned_class' => 'X.4',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603134801000001'] ?? null,
                'nip' => '3603134801000001',
                'assigned_class' => 'X.5',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603130410920001'] ?? null,
                'nip' => '3603130410920001',
                'assigned_class' => 'X.6',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603130303870016'] ?? null,
                'nip' => '3603130303870016',
                'assigned_class' => 'X.7',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603136709870003'] ?? null,
                'nip' => '3603136709870003',
                'assigned_class' => 'X.8',
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603130712930004'] ?? null,
                'nip' => '3603130712930004',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603141012890005'] ?? null,
                'nip' => '3603141012890005',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603135207900007'] ?? null,
                'nip' => '3603135207900007',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['23'] ?? null,
                'nip' => '23',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603132203910001'] ?? null,
                'nip' => '3603132203910001',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603131404910006'] ?? null,
                'nip' => '3603131404910006',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603146208960001'] ?? null,
                'nip' => '3603146208960001',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603135003960009'] ?? null,
                'nip' => '3603135003960009',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603131508840006'] ?? null,
                'nip' => '3603131508840006',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603155007000002'] ?? null,
                'nip' => '3603155007000002',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603142303970005'] ?? null,
                'nip' => '3603142303970005',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603132410940001'] ?? null,
                'nip' => '3603132410940001',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603144506740004'] ?? null,
                'nip' => '3603144506740004',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603132011930004'] ?? null,
                'nip' => '3603132011930004',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603140212650005'] ?? null,
                'nip' => '3603140212650005',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603135712880002'] ?? null,
                'nip' => '3603135712880002',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603130906860002'] ?? null,
                'nip' => '3603130906860002',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3604141301020002'] ?? null,
                'nip' => '3604141301020002',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => $userIds['3603134311850003'] ?? null,
                'nip' => '3603134311850003',
                'assigned_class' => null,
            'created_at' => now(),
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];
        // filter out missing users
        $teachers = array_filter($teachers, fn($t) => $t['user_id'] !== null);
        Teacher::insert($teachers);
    }
}
