name: 🚀 Deploy Laravel (SSH)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY_PRIVATE }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          port: 2223
          script_stop: false
          script: |
            # 1. Pastikan folder tujuan ada
            mkdir -p ~/public_html/domains/presensigentasyaputra.my.id
            cd ~/public_html/domains/presensigentasyaputra.my.id || exit 1

            # 2. Inisialisasi Git jika belum ada
            if [ ! -d ".git" ]; then
              echo "🚀 Folder kosong atau bukan Git repo. Melakukan Clone..."
              git clone https://github.com/${{ github.repository }}.git .
            else
              echo "📦 Folder repo ditemukan. Melakukan Pull..."
              git fetch origin
              git reset --hard origin/main
            fi

            # 3. Install Dependencies
            if [ -f "composer.json" ]; then
              echo "🧰 Install Composer..."
              composer install --no-dev --optimize-autoloader || php ~/bin/composer.phar install --no-dev --optimize-autoloader
            fi

            echo "📦 Install NPM..."
            # Gunakan npm langsung karena server sudah pakai v24.14.1
            npm install && npm run build:filament

            # 4. Optimasi Laravel
            if [ -f "artisan" ]; then
              echo "🚀 Running Artisan commands..."
              php artisan migrate --force
              php artisan config:cache
              php artisan route:cache
              php artisan view:cache
            fi

            echo "✅ Deploy selesai!"
